schedules:
  - cron: '0 0 * * *'
    branches:
      include:
        - main
    always: true

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - stage: 'Preparation'
    jobs:
      - job: 'Source'
        steps:
          - script: |
              registry=https://hub.docker.com/v2/namespaces/$(NAMESPACE)/repositories/$(NAME)/tags
              git clone -q -b $(REPOSITORY_BRANCH) $(REPOSITORY_URL) source
              cd source
              commit=$(git log --branches -1 --pretty=format:"%h")
              [[ $(curl -LI ${registry}/${commit} -o /dev/null -w '%{http_code}\n' -s) = "200" ]] && commit=
              echo "##vso[task.setvariable variable=commit;isOutput=true]${commit}"
              version=$(git describe --tags $(git rev-list --tags --max-count=1))
              [[ $(curl -LI ${registry}/${version} -o /dev/null -w '%{http_code}\n' -s) = "200" ]] && version=
              echo "##vso[task.setvariable variable=version;isOutput=true]${version}"
            name: 'Information'
            displayName: 'Determine the execution of the next stages'

  - stage: 'Staging'
    condition: dependencies.Preparation.outputs['Source.Information.commit']
    dependsOn: 'Preparation'
    variables:
      - name: 'commit'
        value: $[stageDependencies.Preparation.Source.outputs['Information.commit']]
    jobs:
      - job: 'Build'
        steps:
          - task: Docker@2
            displayName: 'Build image'
            inputs:
              containerRegistry: 'Docker Hub'
              repository: '$(NAMESPACE)/$(NAME)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                staging
                $(commit)
              arguments: |
                --build-arg REPOSITORY_URL=$(REPOSITORY_URL)
                --build-arg REPOSITORY_BRANCH=$(REPOSITORY_BRANCH)
                --build-arg REPOSITORY_COMMIT=$(commit)
              addPipelineData: false
          - task: Docker@2
            displayName: 'Publish image'
            inputs:
              containerRegistry: 'Docker Hub'
              repository: '$(NAMESPACE)/$(NAME)'
              command: 'push'
              tags: |
                staging
                $(commit)
              addPipelineData: false

  - stage: 'Production'
    condition: dependencies.Preparation.outputs['Source.Information.version']
    dependsOn: 'Preparation'
    variables:
      - name: 'version'
        value: $[stageDependencies.Preparation.Source.outputs['Information.version']]
    jobs:
      - job: 'Build'
        steps:
          - task: Docker@2
            displayName: 'Build image'
            inputs:
              containerRegistry: 'Docker Hub'
              repository: '$(NAMESPACE)/$(NAME)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(version)
              arguments: |
                --build-arg REPOSITORY_URL=$(REPOSITORY_URL)
                --build-arg REPOSITORY_BRANCH=$(REPOSITORY_BRANCH)
                --build-arg REPOSITORY_TAG=$(version)
              addPipelineData: false
          - task: Docker@2
            displayName: 'Publish image'
            inputs:
              containerRegistry: 'Docker Hub'
              repository: '$(NAMESPACE)/$(NAME)'
              command: 'push'
              tags: |
                latest
                $(version)
              addPipelineData: false
